### ISSUE TITLE
SessionID in consistent position to optimize multiplexed sessions

### ISSUE THREAD

**Issue by donmendelson** [FIXTradingCommunity/fixp-specification#2]
A receiver of sessions that are multiplexed on a shared transport must examine SessionID of each session message in order to demultiplex. Currently, SessionID is in a position dependent on message type. Therefore, the receiver must first examine the message type to determine which decoder to apply to the message. This lookup of decoder type could be optimized out of the demultiplex operation by designing all session messages to have SessionID in the same position. Ideally, it should be the first field in the message.

**Comment by afuruhed** [comment]
Could you shed some more light on this - an example of where you end up with frequently used message  types in a variable position?
The position is encoding specific so one option is to resolve that part of the issue at the encoding level. 
Multiplexing signaling is done per session message as you say, not per application message.
If examining the session id is a problem, I guess also examining the message type has the same issues? If not, how do you know there is a session id to look for, since it is not passed per application message?

**Comment by donmendelson** [comment]
Anders, I agree that this only pertains to session messages, not application messages, and the exact wire format is determined by a message encoding. However, I expect encodings to follow the FIXP spec for the order of fields. In the RC2 spec, SessionID is sometimes the second field, sometimes the third field. I'm just suggesting that it should be in the same position in every _session_ message, and ideally, it should be first field.

**Comment by donmendelson** [comment]
Agreed in principle on 3/21/2016
