### ISSUE TITLE
Finalization Without Termination

### ISSUE THREAD

**Issue by adkapur** [FIXTradingCommunity/fixp-specification#23]
The current FIXP specification proposes finalization of a FIXP session at the end of the day or trading session after which the TCP socket connection is severed with the expectation that a new FIXP session will be Negoitated.

How will this work for markets that need to operate on a 24 hour basis? (either 24x5 or 24x7)

Do we need to be able to finalize a FIXP session without termination in this case since we don't want the FIXP session to live on contiguously for all time (24x7) or even for a whole week (24x5).

**Comment by donmendelson** [comment]
In the SBE message schema for FIXP session messages, sequence number is of type "ordinal", backed by primitive type uint64. This allows for 18,446,744,073,709,551,615 messages to be sent on a FIXP session before re-negotiating. I don't mean to be sarcastic, because I know that in the past other seemingly huge limits have been breached, but do you foresee a problem with that?

**Comment by adkapur** [comment]
Don the issue here is not about a danger of exceeding the sequence numbers available for use but rather the infrastructure required to support persistence of messages and their recovery for a contiguous session.
